// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGvQ4j1rc7w-QBxeVAAf797gnr7ZNJPeA',
    appId: '1:118316373648:web:5eb9cecd8230023b272a15',
    messagingSenderId: '118316373648',
    projectId: 'zonix-93c4a',
    authDomain: 'zonix-93c4a.firebaseapp.com',
    storageBucket: 'zonix-93c4a.firebasestorage.app',
    measurementId: 'G-4EK8DT4XG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGObbnSzBIp8J3qqDSUwEPuI-qfVUhRo',
    appId: '1:118316373648:android:6957ee1028e0644a272a15',
    messagingSenderId: '118316373648',
    projectId: 'zonix-93c4a',
    storageBucket: 'zonix-93c4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0HNJ_b18E3GwVqDvcb-sfH3Yn3xa8dXI',
    appId: '1:118316373648:ios:79a4b94b303c4355272a15',
    messagingSenderId: '118316373648',
    projectId: 'zonix-93c4a',
    storageBucket: 'zonix-93c4a.firebasestorage.app',
    iosBundleId: 'com.example.zonixweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0HNJ_b18E3GwVqDvcb-sfH3Yn3xa8dXI',
    appId: '1:118316373648:ios:79a4b94b303c4355272a15',
    messagingSenderId: '118316373648',
    projectId: 'zonix-93c4a',
    storageBucket: 'zonix-93c4a.firebasestorage.app',
    iosBundleId: 'com.example.zonixweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGvQ4j1rc7w-QBxeVAAf797gnr7ZNJPeA',
    appId: '1:118316373648:web:acde048ac79074be272a15',
    messagingSenderId: '118316373648',
    projectId: 'zonix-93c4a',
    authDomain: 'zonix-93c4a.firebaseapp.com',
    storageBucket: 'zonix-93c4a.firebasestorage.app',
    measurementId: 'G-G0Q7GK7DWW',
  );
}
